[tool.poetry]
name = "ua-text-stressifier"
version = "0.1.0"
description = "Context-aware lexical stress prediction for Ukrainian."
authors = [
    "Anastasiia Senyk",
    "Mykhailo Lukianchuk",
    "Valentyna Robeiko",
    "Yurii Paniv"
]
packages = [{ include = "ua_text_stressifier" }]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
