[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ua-text-stressifier"
version = "0.1.0"
description = "Context-aware lexical stress prediction for Ukrainian."
authors = [
    {name = "Anastasiia Senyk"},
    {name = "Mykhailo Lukianchuk"},
    {name = "Valentyna Robeiko"},
    {name = "Yurii Paniv"}
]
dependencies = [
    "torch==2.7.1",
    "transformers==4.51.3",
]

[tool.setuptools]
packages = [
    "ua_text_stressifier",
    "ua_text_stressifier.accentor"
]

[tool.setuptools.package-data]
"*" = ["*.yaml", "*.json", "*.txt"]